/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PublicRouteImport } from './routes/_public';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as PrivateIndexRouteImport } from './routes/_private/index';
import { Route as PublicInviteIndexRouteImport } from './routes/_public/invite/index';
import { Route as PublicAuthIndexRouteImport } from './routes/_public/auth/index';
import { Route as PrivateProductsIndexRouteImport } from './routes/_private/products/index';
import { Route as PrivateProcessesIndexRouteImport } from './routes/_private/processes/index';
import { Route as PrivateOrdersIndexRouteImport } from './routes/_private/orders/index';
import { Route as PrivateInboxIndexRouteImport } from './routes/_private/inbox/index';
import { Route as PrivateCustomersIndexRouteImport } from './routes/_private/customers/index';
import { Route as PrivateProductsDetailsRouteImport } from './routes/_private/products/details';
import { Route as PrivateProcessesDetailsRouteImport } from './routes/_private/processes/details';
import { Route as PrivateCustomersDetailsRouteImport } from './routes/_private/customers/details';
import { Route as PrivateScheduleProfessionalsIndexRouteImport } from './routes/_private/schedule/professionals/index';
import { Route as PrivateProductsAddIndexRouteImport } from './routes/_private/products/add/index';
import { Route as PrivateProcessesAddIndexRouteImport } from './routes/_private/processes/add/index';
import { Route as PrivateCustomersListIndexRouteImport } from './routes/_private/customers/list/index';
import { Route as PrivateCustomersKanbanIndexRouteImport } from './routes/_private/customers/kanban/index';
import { Route as PrivateCustomersAddIndexRouteImport } from './routes/_private/customers/add/index';
import { Route as PrivateScheduleProfessionalsDetailsRouteImport } from './routes/_private/schedule/professionals/details';
import { Route as PrivateScheduleProfessionalsAddIndexRouteImport } from './routes/_private/schedule/professionals/add/index';

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any);
const PublicInviteIndexRoute = PublicInviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => PublicRoute,
} as any);
const PublicAuthIndexRoute = PublicAuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => PublicRoute,
} as any);
const PrivateProductsIndexRoute = PrivateProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateProcessesIndexRoute = PrivateProcessesIndexRouteImport.update({
  id: '/processes/',
  path: '/processes/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateOrdersIndexRoute = PrivateOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateInboxIndexRoute = PrivateInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateCustomersIndexRoute = PrivateCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateProductsDetailsRoute = PrivateProductsDetailsRouteImport.update({
  id: '/products/details',
  path: '/products/details',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateProcessesDetailsRoute = PrivateProcessesDetailsRouteImport.update({
  id: '/processes/details',
  path: '/processes/details',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateCustomersDetailsRoute = PrivateCustomersDetailsRouteImport.update({
  id: '/customers/details',
  path: '/customers/details',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateScheduleProfessionalsIndexRoute =
  PrivateScheduleProfessionalsIndexRouteImport.update({
    id: '/schedule/professionals/',
    path: '/schedule/professionals/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateProductsAddIndexRoute = PrivateProductsAddIndexRouteImport.update({
  id: '/products/add/',
  path: '/products/add/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateProcessesAddIndexRoute =
  PrivateProcessesAddIndexRouteImport.update({
    id: '/processes/add/',
    path: '/processes/add/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateCustomersListIndexRoute =
  PrivateCustomersListIndexRouteImport.update({
    id: '/customers/list/',
    path: '/customers/list/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateCustomersKanbanIndexRoute =
  PrivateCustomersKanbanIndexRouteImport.update({
    id: '/customers/kanban/',
    path: '/customers/kanban/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateCustomersAddIndexRoute =
  PrivateCustomersAddIndexRouteImport.update({
    id: '/customers/add/',
    path: '/customers/add/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateScheduleProfessionalsDetailsRoute =
  PrivateScheduleProfessionalsDetailsRouteImport.update({
    id: '/schedule/professionals/details',
    path: '/schedule/professionals/details',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateScheduleProfessionalsAddIndexRoute =
  PrivateScheduleProfessionalsAddIndexRouteImport.update({
    id: '/schedule/professionals/add/',
    path: '/schedule/professionals/add/',
    getParentRoute: () => PrivateRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute;
  '/customers/details': typeof PrivateCustomersDetailsRoute;
  '/processes/details': typeof PrivateProcessesDetailsRoute;
  '/products/details': typeof PrivateProductsDetailsRoute;
  '/customers/': typeof PrivateCustomersIndexRoute;
  '/inbox/': typeof PrivateInboxIndexRoute;
  '/orders/': typeof PrivateOrdersIndexRoute;
  '/processes/': typeof PrivateProcessesIndexRoute;
  '/products/': typeof PrivateProductsIndexRoute;
  '/auth/': typeof PublicAuthIndexRoute;
  '/invite/': typeof PublicInviteIndexRoute;
  '/schedule/professionals/details': typeof PrivateScheduleProfessionalsDetailsRoute;
  '/customers/add/': typeof PrivateCustomersAddIndexRoute;
  '/customers/kanban/': typeof PrivateCustomersKanbanIndexRoute;
  '/customers/list/': typeof PrivateCustomersListIndexRoute;
  '/processes/add/': typeof PrivateProcessesAddIndexRoute;
  '/products/add/': typeof PrivateProductsAddIndexRoute;
  '/schedule/professionals/': typeof PrivateScheduleProfessionalsIndexRoute;
  '/schedule/professionals/add/': typeof PrivateScheduleProfessionalsAddIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute;
  '/customers/details': typeof PrivateCustomersDetailsRoute;
  '/processes/details': typeof PrivateProcessesDetailsRoute;
  '/products/details': typeof PrivateProductsDetailsRoute;
  '/customers': typeof PrivateCustomersIndexRoute;
  '/inbox': typeof PrivateInboxIndexRoute;
  '/orders': typeof PrivateOrdersIndexRoute;
  '/processes': typeof PrivateProcessesIndexRoute;
  '/products': typeof PrivateProductsIndexRoute;
  '/auth': typeof PublicAuthIndexRoute;
  '/invite': typeof PublicInviteIndexRoute;
  '/schedule/professionals/details': typeof PrivateScheduleProfessionalsDetailsRoute;
  '/customers/add': typeof PrivateCustomersAddIndexRoute;
  '/customers/kanban': typeof PrivateCustomersKanbanIndexRoute;
  '/customers/list': typeof PrivateCustomersListIndexRoute;
  '/processes/add': typeof PrivateProcessesAddIndexRoute;
  '/products/add': typeof PrivateProductsAddIndexRoute;
  '/schedule/professionals': typeof PrivateScheduleProfessionalsIndexRoute;
  '/schedule/professionals/add': typeof PrivateScheduleProfessionalsAddIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_private': typeof PrivateRouteWithChildren;
  '/_public': typeof PublicRouteWithChildren;
  '/_private/': typeof PrivateIndexRoute;
  '/_private/customers/details': typeof PrivateCustomersDetailsRoute;
  '/_private/processes/details': typeof PrivateProcessesDetailsRoute;
  '/_private/products/details': typeof PrivateProductsDetailsRoute;
  '/_private/customers/': typeof PrivateCustomersIndexRoute;
  '/_private/inbox/': typeof PrivateInboxIndexRoute;
  '/_private/orders/': typeof PrivateOrdersIndexRoute;
  '/_private/processes/': typeof PrivateProcessesIndexRoute;
  '/_private/products/': typeof PrivateProductsIndexRoute;
  '/_public/auth/': typeof PublicAuthIndexRoute;
  '/_public/invite/': typeof PublicInviteIndexRoute;
  '/_private/schedule/professionals/details': typeof PrivateScheduleProfessionalsDetailsRoute;
  '/_private/customers/add/': typeof PrivateCustomersAddIndexRoute;
  '/_private/customers/kanban/': typeof PrivateCustomersKanbanIndexRoute;
  '/_private/customers/list/': typeof PrivateCustomersListIndexRoute;
  '/_private/processes/add/': typeof PrivateProcessesAddIndexRoute;
  '/_private/products/add/': typeof PrivateProductsAddIndexRoute;
  '/_private/schedule/professionals/': typeof PrivateScheduleProfessionalsIndexRoute;
  '/_private/schedule/professionals/add/': typeof PrivateScheduleProfessionalsAddIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/customers/details'
    | '/processes/details'
    | '/products/details'
    | '/customers/'
    | '/inbox/'
    | '/orders/'
    | '/processes/'
    | '/products/'
    | '/auth/'
    | '/invite/'
    | '/schedule/professionals/details'
    | '/customers/add/'
    | '/customers/kanban/'
    | '/customers/list/'
    | '/processes/add/'
    | '/products/add/'
    | '/schedule/professionals/'
    | '/schedule/professionals/add/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/customers/details'
    | '/processes/details'
    | '/products/details'
    | '/customers'
    | '/inbox'
    | '/orders'
    | '/processes'
    | '/products'
    | '/auth'
    | '/invite'
    | '/schedule/professionals/details'
    | '/customers/add'
    | '/customers/kanban'
    | '/customers/list'
    | '/processes/add'
    | '/products/add'
    | '/schedule/professionals'
    | '/schedule/professionals/add';
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/'
    | '/_private/customers/details'
    | '/_private/processes/details'
    | '/_private/products/details'
    | '/_private/customers/'
    | '/_private/inbox/'
    | '/_private/orders/'
    | '/_private/processes/'
    | '/_private/products/'
    | '/_public/auth/'
    | '/_public/invite/'
    | '/_private/schedule/professionals/details'
    | '/_private/customers/add/'
    | '/_private/customers/kanban/'
    | '/_private/customers/list/'
    | '/_private/processes/add/'
    | '/_private/products/add/'
    | '/_private/schedule/professionals/'
    | '/_private/schedule/professionals/add/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren;
  PublicRoute: typeof PublicRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private/': {
      id: '/_private/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PrivateIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_public/invite/': {
      id: '/_public/invite/';
      path: '/invite';
      fullPath: '/invite/';
      preLoaderRoute: typeof PublicInviteIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_public/auth/': {
      id: '/_public/auth/';
      path: '/auth';
      fullPath: '/auth/';
      preLoaderRoute: typeof PublicAuthIndexRouteImport;
      parentRoute: typeof PublicRoute;
    };
    '/_private/products/': {
      id: '/_private/products/';
      path: '/products';
      fullPath: '/products/';
      preLoaderRoute: typeof PrivateProductsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/processes/': {
      id: '/_private/processes/';
      path: '/processes';
      fullPath: '/processes/';
      preLoaderRoute: typeof PrivateProcessesIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/orders/': {
      id: '/_private/orders/';
      path: '/orders';
      fullPath: '/orders/';
      preLoaderRoute: typeof PrivateOrdersIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/inbox/': {
      id: '/_private/inbox/';
      path: '/inbox';
      fullPath: '/inbox/';
      preLoaderRoute: typeof PrivateInboxIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/': {
      id: '/_private/customers/';
      path: '/customers';
      fullPath: '/customers/';
      preLoaderRoute: typeof PrivateCustomersIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/products/details': {
      id: '/_private/products/details';
      path: '/products/details';
      fullPath: '/products/details';
      preLoaderRoute: typeof PrivateProductsDetailsRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/processes/details': {
      id: '/_private/processes/details';
      path: '/processes/details';
      fullPath: '/processes/details';
      preLoaderRoute: typeof PrivateProcessesDetailsRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/details': {
      id: '/_private/customers/details';
      path: '/customers/details';
      fullPath: '/customers/details';
      preLoaderRoute: typeof PrivateCustomersDetailsRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/schedule/professionals/': {
      id: '/_private/schedule/professionals/';
      path: '/schedule/professionals';
      fullPath: '/schedule/professionals/';
      preLoaderRoute: typeof PrivateScheduleProfessionalsIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/products/add/': {
      id: '/_private/products/add/';
      path: '/products/add';
      fullPath: '/products/add/';
      preLoaderRoute: typeof PrivateProductsAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/processes/add/': {
      id: '/_private/processes/add/';
      path: '/processes/add';
      fullPath: '/processes/add/';
      preLoaderRoute: typeof PrivateProcessesAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/list/': {
      id: '/_private/customers/list/';
      path: '/customers/list';
      fullPath: '/customers/list/';
      preLoaderRoute: typeof PrivateCustomersListIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/kanban/': {
      id: '/_private/customers/kanban/';
      path: '/customers/kanban';
      fullPath: '/customers/kanban/';
      preLoaderRoute: typeof PrivateCustomersKanbanIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/add/': {
      id: '/_private/customers/add/';
      path: '/customers/add';
      fullPath: '/customers/add/';
      preLoaderRoute: typeof PrivateCustomersAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/schedule/professionals/details': {
      id: '/_private/schedule/professionals/details';
      path: '/schedule/professionals/details';
      fullPath: '/schedule/professionals/details';
      preLoaderRoute: typeof PrivateScheduleProfessionalsDetailsRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/schedule/professionals/add/': {
      id: '/_private/schedule/professionals/add/';
      path: '/schedule/professionals/add';
      fullPath: '/schedule/professionals/add/';
      preLoaderRoute: typeof PrivateScheduleProfessionalsAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute;
  PrivateCustomersDetailsRoute: typeof PrivateCustomersDetailsRoute;
  PrivateProcessesDetailsRoute: typeof PrivateProcessesDetailsRoute;
  PrivateProductsDetailsRoute: typeof PrivateProductsDetailsRoute;
  PrivateCustomersIndexRoute: typeof PrivateCustomersIndexRoute;
  PrivateInboxIndexRoute: typeof PrivateInboxIndexRoute;
  PrivateOrdersIndexRoute: typeof PrivateOrdersIndexRoute;
  PrivateProcessesIndexRoute: typeof PrivateProcessesIndexRoute;
  PrivateProductsIndexRoute: typeof PrivateProductsIndexRoute;
  PrivateScheduleProfessionalsDetailsRoute: typeof PrivateScheduleProfessionalsDetailsRoute;
  PrivateCustomersAddIndexRoute: typeof PrivateCustomersAddIndexRoute;
  PrivateCustomersKanbanIndexRoute: typeof PrivateCustomersKanbanIndexRoute;
  PrivateCustomersListIndexRoute: typeof PrivateCustomersListIndexRoute;
  PrivateProcessesAddIndexRoute: typeof PrivateProcessesAddIndexRoute;
  PrivateProductsAddIndexRoute: typeof PrivateProductsAddIndexRoute;
  PrivateScheduleProfessionalsIndexRoute: typeof PrivateScheduleProfessionalsIndexRoute;
  PrivateScheduleProfessionalsAddIndexRoute: typeof PrivateScheduleProfessionalsAddIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateCustomersDetailsRoute: PrivateCustomersDetailsRoute,
  PrivateProcessesDetailsRoute: PrivateProcessesDetailsRoute,
  PrivateProductsDetailsRoute: PrivateProductsDetailsRoute,
  PrivateCustomersIndexRoute: PrivateCustomersIndexRoute,
  PrivateInboxIndexRoute: PrivateInboxIndexRoute,
  PrivateOrdersIndexRoute: PrivateOrdersIndexRoute,
  PrivateProcessesIndexRoute: PrivateProcessesIndexRoute,
  PrivateProductsIndexRoute: PrivateProductsIndexRoute,
  PrivateScheduleProfessionalsDetailsRoute:
    PrivateScheduleProfessionalsDetailsRoute,
  PrivateCustomersAddIndexRoute: PrivateCustomersAddIndexRoute,
  PrivateCustomersKanbanIndexRoute: PrivateCustomersKanbanIndexRoute,
  PrivateCustomersListIndexRoute: PrivateCustomersListIndexRoute,
  PrivateProcessesAddIndexRoute: PrivateProcessesAddIndexRoute,
  PrivateProductsAddIndexRoute: PrivateProductsAddIndexRoute,
  PrivateScheduleProfessionalsIndexRoute:
    PrivateScheduleProfessionalsIndexRoute,
  PrivateScheduleProfessionalsAddIndexRoute:
    PrivateScheduleProfessionalsAddIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

interface PublicRouteChildren {
  PublicAuthIndexRoute: typeof PublicAuthIndexRoute;
  PublicInviteIndexRoute: typeof PublicInviteIndexRoute;
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthIndexRoute: PublicAuthIndexRoute,
  PublicInviteIndexRoute: PublicInviteIndexRoute,
};

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
