/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as InviteIndexRouteImport } from './routes/invite/index';
import { Route as AuthIndexRouteImport } from './routes/auth/index';
import { Route as PrivateIndexRouteImport } from './routes/_private/index';
import { Route as PrivateCustomersIndexRouteImport } from './routes/_private/customers/index';
import { Route as PrivateCustomersKanbanIndexRouteImport } from './routes/_private/customers/kanban/index';

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateCustomersIndexRoute = PrivateCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateCustomersKanbanIndexRoute =
  PrivateCustomersKanbanIndexRouteImport.update({
    id: '/customers/kanban/',
    path: '/customers/kanban/',
    getParentRoute: () => PrivateRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute;
  '/auth/': typeof AuthIndexRoute;
  '/invite/': typeof InviteIndexRoute;
  '/customers/': typeof PrivateCustomersIndexRoute;
  '/customers/kanban/': typeof PrivateCustomersKanbanIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute;
  '/auth': typeof AuthIndexRoute;
  '/invite': typeof InviteIndexRoute;
  '/customers': typeof PrivateCustomersIndexRoute;
  '/customers/kanban': typeof PrivateCustomersKanbanIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_private': typeof PrivateRouteWithChildren;
  '/_private/': typeof PrivateIndexRoute;
  '/auth/': typeof AuthIndexRoute;
  '/invite/': typeof InviteIndexRoute;
  '/_private/customers/': typeof PrivateCustomersIndexRoute;
  '/_private/customers/kanban/': typeof PrivateCustomersKanbanIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/auth/' | '/invite/' | '/customers/' | '/customers/kanban/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/auth' | '/invite' | '/customers' | '/customers/kanban';
  id:
    | '__root__'
    | '/_private'
    | '/_private/'
    | '/auth/'
    | '/invite/'
    | '/_private/customers/'
    | '/_private/customers/kanban/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren;
  AuthIndexRoute: typeof AuthIndexRoute;
  InviteIndexRoute: typeof InviteIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/invite/': {
      id: '/invite/';
      path: '/invite';
      fullPath: '/invite/';
      preLoaderRoute: typeof InviteIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/': {
      id: '/auth/';
      path: '/auth';
      fullPath: '/auth/';
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private/': {
      id: '/_private/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PrivateIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/': {
      id: '/_private/customers/';
      path: '/customers';
      fullPath: '/customers/';
      preLoaderRoute: typeof PrivateCustomersIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/kanban/': {
      id: '/_private/customers/kanban/';
      path: '/customers/kanban';
      fullPath: '/customers/kanban/';
      preLoaderRoute: typeof PrivateCustomersKanbanIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute;
  PrivateCustomersIndexRoute: typeof PrivateCustomersIndexRoute;
  PrivateCustomersKanbanIndexRoute: typeof PrivateCustomersKanbanIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateCustomersIndexRoute: PrivateCustomersIndexRoute,
  PrivateCustomersKanbanIndexRoute: PrivateCustomersKanbanIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  InviteIndexRoute: InviteIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
