/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PrivateRouteImport } from './routes/_private';
import { Route as InviteIndexRouteImport } from './routes/invite/index';
import { Route as AuthIndexRouteImport } from './routes/auth/index';
import { Route as PrivateIndexRouteImport } from './routes/_private/index';
import { Route as PrivateCustomersIndexRouteImport } from './routes/_private/customers/index';
import { Route as PrivateCustomersDetailsRouteImport } from './routes/_private/customers/details';
import { Route as PrivateProcessesAddIndexRouteImport } from './routes/_private/processes/add/index';
import { Route as PrivateCustomersKanbanIndexRouteImport } from './routes/_private/customers/kanban/index';
import { Route as PrivateCustomersAddIndexRouteImport } from './routes/_private/customers/add/index';

const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any);
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateCustomersIndexRoute = PrivateCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateCustomersDetailsRoute = PrivateCustomersDetailsRouteImport.update({
  id: '/customers/details',
  path: '/customers/details',
  getParentRoute: () => PrivateRoute,
} as any);
const PrivateProcessesAddIndexRoute =
  PrivateProcessesAddIndexRouteImport.update({
    id: '/processes/add/',
    path: '/processes/add/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateCustomersKanbanIndexRoute =
  PrivateCustomersKanbanIndexRouteImport.update({
    id: '/customers/kanban/',
    path: '/customers/kanban/',
    getParentRoute: () => PrivateRoute,
  } as any);
const PrivateCustomersAddIndexRoute =
  PrivateCustomersAddIndexRouteImport.update({
    id: '/customers/add/',
    path: '/customers/add/',
    getParentRoute: () => PrivateRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute;
  '/auth/': typeof AuthIndexRoute;
  '/invite/': typeof InviteIndexRoute;
  '/customers/details': typeof PrivateCustomersDetailsRoute;
  '/customers/': typeof PrivateCustomersIndexRoute;
  '/customers/add/': typeof PrivateCustomersAddIndexRoute;
  '/customers/kanban/': typeof PrivateCustomersKanbanIndexRoute;
  '/processes/add/': typeof PrivateProcessesAddIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute;
  '/auth': typeof AuthIndexRoute;
  '/invite': typeof InviteIndexRoute;
  '/customers/details': typeof PrivateCustomersDetailsRoute;
  '/customers': typeof PrivateCustomersIndexRoute;
  '/customers/add': typeof PrivateCustomersAddIndexRoute;
  '/customers/kanban': typeof PrivateCustomersKanbanIndexRoute;
  '/processes/add': typeof PrivateProcessesAddIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_private': typeof PrivateRouteWithChildren;
  '/_private/': typeof PrivateIndexRoute;
  '/auth/': typeof AuthIndexRoute;
  '/invite/': typeof InviteIndexRoute;
  '/_private/customers/details': typeof PrivateCustomersDetailsRoute;
  '/_private/customers/': typeof PrivateCustomersIndexRoute;
  '/_private/customers/add/': typeof PrivateCustomersAddIndexRoute;
  '/_private/customers/kanban/': typeof PrivateCustomersKanbanIndexRoute;
  '/_private/processes/add/': typeof PrivateProcessesAddIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/auth/'
    | '/invite/'
    | '/customers/details'
    | '/customers/'
    | '/customers/add/'
    | '/customers/kanban/'
    | '/processes/add/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/auth'
    | '/invite'
    | '/customers/details'
    | '/customers'
    | '/customers/add'
    | '/customers/kanban'
    | '/processes/add';
  id:
    | '__root__'
    | '/_private'
    | '/_private/'
    | '/auth/'
    | '/invite/'
    | '/_private/customers/details'
    | '/_private/customers/'
    | '/_private/customers/add/'
    | '/_private/customers/kanban/'
    | '/_private/processes/add/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren;
  AuthIndexRoute: typeof AuthIndexRoute;
  InviteIndexRoute: typeof InviteIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof PrivateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/invite/': {
      id: '/invite/';
      path: '/invite';
      fullPath: '/invite/';
      preLoaderRoute: typeof InviteIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/': {
      id: '/auth/';
      path: '/auth';
      fullPath: '/auth/';
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_private/': {
      id: '/_private/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PrivateIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/': {
      id: '/_private/customers/';
      path: '/customers';
      fullPath: '/customers/';
      preLoaderRoute: typeof PrivateCustomersIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/details': {
      id: '/_private/customers/details';
      path: '/customers/details';
      fullPath: '/customers/details';
      preLoaderRoute: typeof PrivateCustomersDetailsRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/processes/add/': {
      id: '/_private/processes/add/';
      path: '/processes/add';
      fullPath: '/processes/add/';
      preLoaderRoute: typeof PrivateProcessesAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/kanban/': {
      id: '/_private/customers/kanban/';
      path: '/customers/kanban';
      fullPath: '/customers/kanban/';
      preLoaderRoute: typeof PrivateCustomersKanbanIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
    '/_private/customers/add/': {
      id: '/_private/customers/add/';
      path: '/customers/add';
      fullPath: '/customers/add/';
      preLoaderRoute: typeof PrivateCustomersAddIndexRouteImport;
      parentRoute: typeof PrivateRoute;
    };
  }
}

interface PrivateRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute;
  PrivateCustomersDetailsRoute: typeof PrivateCustomersDetailsRoute;
  PrivateCustomersIndexRoute: typeof PrivateCustomersIndexRoute;
  PrivateCustomersAddIndexRoute: typeof PrivateCustomersAddIndexRoute;
  PrivateCustomersKanbanIndexRoute: typeof PrivateCustomersKanbanIndexRoute;
  PrivateProcessesAddIndexRoute: typeof PrivateProcessesAddIndexRoute;
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateCustomersDetailsRoute: PrivateCustomersDetailsRoute,
  PrivateCustomersIndexRoute: PrivateCustomersIndexRoute,
  PrivateCustomersAddIndexRoute: PrivateCustomersAddIndexRoute,
  PrivateCustomersKanbanIndexRoute: PrivateCustomersKanbanIndexRoute,
  PrivateProcessesAddIndexRoute: PrivateProcessesAddIndexRoute,
};

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  InviteIndexRoute: InviteIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
