// Dicionário fixo pt-BR: toda string voltada ao usuário do app passa
// por `t(key)` — sem biblioteca de i18n nem seletor de idioma. Inclui as
// chaves que a API devolve em `message` (API_MESSAGE_KEYS de
// @crm/contracts), traduzidas por lib/api/client.api.ts.
// Regras de uso e criação de chave: ver apps/web/CLAUDE.md
// ("Tradução (t()) e datas"). Resumo: chave plana, snake_case, nomeia
// O TEXTO (nunca a tela/feature/papel); busca e reaproveita uma chave
// genérica existente antes de criar uma nova; nova chave só 1:1 com o
// texto, sem template/concat pra montar chave dinâmica.
const translations: Record<string, string> = {
  // Campos genéricos
  email: 'E-mail',
  password: 'Senha',
  name: 'Nome',
  phone: 'Telefone',
  document: 'Documento',
  status: 'Status',
  title: 'Título',
  description: 'Descrição',
  notes: 'Observações',
  date: 'Data',
  time: 'Hora',
  start: 'Início',
  end: 'Fim',
  start_date: 'Data de início',
  start_time: 'Hora de início',
  end_date: 'Data de fim',
  end_time: 'Hora de fim',
  price: 'Preço',
  stock: 'Estoque',
  sku: 'SKU',
  items: 'Itens',
  total: 'Total',
  payment: 'Pagamento',
  mode: 'Modo',
  assignee: 'Responsável',
  last_activity: 'Última atividade',
  unread: 'Não lida',
  window_24h: 'Janela 24h',
  stage: 'Etapa',
  role: 'Papel',
  color: 'Cor',
  slot_duration: 'Duração do horário (min)',
  max_slots_per_reply: 'Máximo de horários por resposta',
  column_name: 'Nome da coluna',
  process_type: 'Tipo de processo',
  weekly_schedule: 'Grade semanal',
  invite_to: 'Convite para',
  loading: 'Carregando…',
  // Ações
  save: 'Salvar',
  cancel: 'Cancelar',
  edit: 'Editar',
  confirm: 'Confirmar',
  close: 'Fechar',
  back: 'Voltar',
  add: 'Adicionar',
  add_column: 'Adicionar coluna',
  remove: 'Remover',
  search: 'Buscar…',
  send: 'Enviar',
  resend: 'Reenviar',
  view: 'Ver',
  download: 'Baixar',
  approve: 'Aprovar',
  reject: 'Rejeitar',
  take_over: 'Assumir',
  release: 'Liberar',
  reschedule: 'Remarcar',
  cancel_appointment: 'Cancelar agendamento',
  request_confirmation: 'Pedir confirmação',
  confirm_attendance: 'Confirmar presença',
  will_not_attend: 'Não vou comparecer',
  notify_via_whatsapp: 'Avisar pelo WhatsApp',
  open_in_whatsapp: 'Abrir no WhatsApp',
  move_up: 'Mover para cima',
  move_down: 'Mover para baixo',
  manage_columns: 'Gerenciar colunas',
  show_inactive: 'Mostrar inativos',
  sign_in: 'Entrar',
  sign_out: 'Sair',
  create_account: 'Criar conta',
  accept_invite: 'Aceitar convite',
  new_customer: 'Novo cliente',
  new_process: 'Novo processo',
  new_product: 'Novo produto',
  new_professional: 'Novo profissional',
  new_space: 'Novo ambiente',
  new_board: 'Novo quadro',
  new_card: 'Novo card',
  new_appointment: 'Novo agendamento',
  new_block: 'Novo bloqueio',
  // Entidades, navegação e seções
  customer: 'Cliente',
  customers: 'Clientes',
  process: 'Processo',
  processes: 'Processos',
  products: 'Produtos',
  catalog: 'Catálogo',
  order: 'Pedido',
  orders: 'Pedidos',
  professional: 'Profissional',
  professionals: 'Profissionais',
  space: 'Ambiente',
  spaces: 'Ambientes',
  appointment: 'Agendamento',
  appointment_confirmation: 'Confirmação de agendamento',
  block: 'Bloqueio',
  calendar: 'Calendário',
  settings: 'Configurações',
  inbox: 'Caixa de entrada',
  boards: 'Quadros',
  card: 'Card',
  cards: 'Cards',
  columns: 'Colunas',
  kanban: 'Kanban',
  table: 'Tabela',
  list: 'Listagem',
  details: 'Detalhes',
  additional_details: 'Detalhes adicionais',
  information: 'Informações',
  identification: 'Identificação',
  credentials: 'Credenciais de acesso',
  your_data: 'Seus dados',
  values: 'Valores',
  main_navigation: 'Navegação principal',
  user_menu: 'Menu do usuário',
  theme: 'Tema',
  text_size: 'Tamanho do texto',
  page: 'Página',
  previous_page: 'Página anterior',
  next_page: 'Próxima página',
  previous: 'Anterior',
  next: 'Próximo',
  today: 'Hoje',
  day: 'Dia',
  week: 'Semana',
  month: 'Mês',
  home: 'Início',
  schedule: 'Agenda',
  more: 'Mais',
  // Estados e enums
  active: 'Ativo',
  inactive: 'Inativo',
  all: 'Todos',
  none: 'Nenhum',
  yes: 'Sim',
  no_status: 'Sem status',
  bot: 'Bot',
  human: 'Humano',
  open: 'Aberta',
  closed: 'Fechada',
  failed: 'Falhou',
  light: 'Claro',
  dark: 'Escuro',
  system: 'Sistema',
  small: 'Pequeno',
  medium: 'Médio',
  large: 'Grande',
  sunday: 'Domingo',
  monday: 'Segunda-feira',
  tuesday: 'Terça-feira',
  wednesday: 'Quarta-feira',
  thursday: 'Quinta-feira',
  friday: 'Sexta-feira',
  saturday: 'Sábado',
  attended: 'Compareceu',
  pending: 'Pendente',
  pending_approval: 'Pendente',
  confirmed: 'Confirmado',
  rejected: 'Rejeitado',
  payment_expired: 'Pagamento expirado',
  paid: 'Pago',
  expired: 'Expirado',
  refunded: 'Reembolsado',
  canceled: 'Cancelado',
  completed: 'Concluído',
  no_show: 'Não compareceu',
  canceled_by_customer: 'Cancelado pelo cliente',
  canceled_by_operator: 'Cancelado pelo operador',
  // Placeholders e exemplos
  choose_day: 'Escolha o dia',
  choose_process_type: 'Escolha um tipo de processo',
  date_format: 'dd/mm/aaaa',
  time_format: 'hh:mm',
  optional_reason: 'Motivo (opcional)',
  write_message: 'Escreva uma mensagem…',
  example_person_name: 'Ex.: Maria Silva',
  example_phone: 'Ex.: 11999999999',
  example_document: 'Ex.: 000.000.000-00',
  example_product_name: 'Ex.: Camiseta Branca P',
  example_sku: 'Ex.: CAM-BR-P',
  example_number: 'Ex.: 10',
  example_description: 'Ex.: Descrição curta.',
  example_space_name: 'Ex.: Sala 1',
  example_board_name: 'Ex.: Vendas',
  example_column_name: 'Ex.: A fazer',
  example_block_title: 'Ex.: Feriado, folga ou reunião',
  // Mensagens e subtítulos
  not_found: 'Nenhum registro encontrado.',
  adjust_filters: 'Ajuste os filtros ou tente outro termo de busca.',
  no_messages: 'Nenhuma mensagem ainda.',
  unsupported_message: 'Tipo de mensagem não suportado nesta tela.',
  select_conversation: 'Selecione uma conversa na fila para ver o histórico.',
  conversation_not_found: 'Conversa não encontrada nesta página da fila. Ajuste os filtros ou a paginação.',
  select_customer_for_processes: 'Selecione um cliente para ver ou criar processos.',
  whatsapp_window_closed: 'A janela de 24h está fechada. Continue a conversa pelo seu WhatsApp.',
  customer_notified: 'Cliente avisado.',
  created_successfully: 'Criado com sucesso.',
  removed_successfully: 'Removido com sucesso.',
  signed_in_successfully: 'Login realizado com sucesso.',
  signed_out_successfully: 'Logout realizado com sucesso.',
  invite_email_failed: 'Convite criado, mas o envio do e-mail falhou.',
  invalid_link: 'Link inválido.',
  expired_link: 'Link expirado.',
  used_link: 'Link já utilizado.',
  custom_fields: 'Campos extras configurados pela sua empresa.',
  basic_contact_data: 'Dados básicos para identificar e contatar o cliente.',
  enter_email_and_password: 'Informe seu e-mail e senha cadastrados.',
  set_name_and_password: 'Defina seu nome e senha para concluir o cadastro.',
  catalog_and_stock_data: 'Dados usados no catálogo e na conferência de estoque.',
  name_and_slot_duration: 'Nome e duração padrão dos horários de atendimento.',
  set_available_hours: 'Defina os horários em que o profissional está disponível para agendamentos.',
  space_name_for_appointments: 'Nome do ambiente usado nos agendamentos.',
  max_suggested_slots: 'Quantidade máxima de horários sugeridos em cada resposta automática do agendamento.',
  choose_appointment_details: 'Escolha cliente, profissional, data e horário do atendimento.',
  choose_new_date_and_time: 'Escolha a nova data, horário e, se necessário, o profissional.',
  blocks_new_appointments: 'Impede novos agendamentos deste profissional durante o período informado.',
  name_and_description: 'Nome e descrição.',
  set_initial_columns: 'Defina as colunas iniciais do quadro — é possível ajustar depois.',
  title_description_and_references:
    'Título, descrição e referências opcionais (cliente, processo, pedido, responsável).',
  customize_columns: 'Renomeie, defina uma cor, reordene ou remova as colunas deste quadro.',
  review_and_confirm_attendance: 'Revise os detalhes do seu agendamento e confirme sua presença.',
  contact_for_questions: 'Em caso de dúvidas, entre em contato com o estabelecimento.',
  // Erros
  load_error: 'Não foi possível carregar os dados.',
  create_error: 'Não foi possível criar o registro.',
  save_error: 'Não foi possível salvar as alterações.',
  remove_error: 'Não foi possível remover o registro.',
  move_error: 'Não foi possível mover. Tente novamente.',
  send_error: 'Não foi possível enviar.',
  action_error: 'Não foi possível concluir a ação. Tente novamente.',
  invalid_session: 'Sessão inválida.',
  connection_error: 'Não foi possível conectar ao servidor. Tente novamente.',
  internal_error: 'Erro interno do servidor. Tente novamente.',
  invalid_data: 'Dados inválidos. Revise as informações e tente novamente.',
  status_required: 'O status é obrigatório.',
  invalid_credentials: 'E-mail ou senha inválidos.',
  invalid_access: 'Acesso inválido.',
  no_permission: 'Você não tem permissão para realizar esta ação.',
  company_link_required: 'Conclua o vínculo com uma empresa antes de continuar.',
  too_many_attempts: 'Muitas tentativas. Tente novamente em alguns minutos.',
  already_exists: 'Registro já existente.',
  already_finalized: 'Este registro já foi finalizado.',
  email_already_registered: 'Este e-mail já pertence a um usuário.',
  pending_invite_exists: 'Já existe um convite pendente para este e-mail.',
  template_not_found: 'Modelo de campos não encontrado.',
  archived_template: 'Modelo de campos arquivado.',
  template_without_stages: 'O modelo não tem etapas configuradas.',
  invalid_stage: 'Etapa inválida.',
  outdated_version: 'Versão desatualizada. Recarregue a página e tente novamente.',
  migration_plan_required: 'Mudança destrutiva exige um plano de migração.',
  unavailable_time: 'Horário indisponível.',
  no_linked_customer: 'Nenhum cliente vinculado.',
  at_least_one_column: 'É necessário ao menos uma coluna.',
  column_not_empty: 'A coluna precisa estar vazia para ser removida.',
  conversation_already_assigned: 'Conversa já assumida por outro operador.',
  only_failed_messages_can_be_resent: 'Só mensagens com falha podem ser reenviadas.',
  invalid_asaas_key: 'Chave Asaas inválida ou revogada.',
};

// Índice 0=domingo..6=sábado (Date#getUTCDay), mesma faixa de
// `weeklySchedule` — usar pra chave dinâmica de dia da semana, nunca
// montar `weekday.${n}`.
export const WEEKDAY_KEYS = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'] as const;

export const t = (key: string): string => translations[key] ?? key;

// `t()` não distingue "chave existe" de "chave sumiu" (os dois caem no ??
// key) — este helper existe só pro teste-guarda (translate.helper.unit.test.ts)
// conseguir validar de verdade que toda chave usada no código está aqui.
export const translationKeys = new Set(Object.keys(translations));
