// Dicionário fixo pt-BR (T28 — feature crm-web-shell fecha o SPEC_DEVIATION
// que apontava pra cá): toda string voltada ao usuário do app passa por
// `t(key)`, telas novas E existentes (auth/invite/private), sem biblioteca
// de i18n nem seletor de idioma (spec.md, Assumptions — mesmo padrão do
// `translations.json` plano do front de referência).
const translations: Record<string, string> = {
  email: 'E-mail',
  password: 'Senha',
  name: 'Nome',
  phone: 'Telefone',
  document: 'Documento',
  status: 'Status',
  save: 'Salvar',
  cancel: 'Cancelar',
  edit: 'Editar',
  confirm: 'Confirmar',
  back: 'Voltar',
  'date.pick': 'Escolha o dia',
  customers: 'Clientes',
  'customer.create.title': 'Novo cliente',
  'customer.create.error': 'Não foi possível criar o cliente.',
  'customer.details.title': 'Detalhe do cliente',
  'customer.processes.title': 'Processos',
  'customer.edit.error': 'Não foi possível salvar as alterações.',
  'process.create.title': 'Novo processo',
  'process.create.error': 'Não foi possível criar o processo.',
  'process.create.success': 'Processo criado com sucesso.',
  'process.template.placeholder': 'Escolha um tipo de processo',
  'process.new.action': 'Novo processo',
  'process.details.title': 'Detalhe do processo',
  'process.values.error': 'Não foi possível salvar os valores do processo.',
  'process.stage.label': 'Etapa',
  'process.stage.error': 'Não foi possível avançar a etapa do processo.',
  'auth.signin.title': 'Entrar',
  'auth.signin.submit': 'Entrar',
  'auth.signin.error': 'Não foi possível entrar.',
  'invite.accept.title': 'Aceitar convite',
  'invite.accept.submit': 'Criar conta',
  'invite.accept.missing_token': 'Link de convite inválido.',
  'invite.accept.invited_to': 'Convite para',
  'invite.accept.error': 'Não foi possível concluir o cadastro.',
  'invite.accept.invalid': 'Convite inválido.',
  loading: 'Carregando…',
  add: 'Adicionar',
  remove: 'Remover',
  'not.found': 'Nenhum registro encontrado.',
  'not.found.description': 'Ajuste os filtros ou tente outro termo de busca.',
  'search.placeholder': 'Buscar…',
  'table.page': 'Página',
  'previous.page': 'Página anterior',
  'next.page': 'Próxima página',
  'customer.status.none': 'Sem status',
  'kanban.move.error': 'Não foi possível mover o cliente. Tente novamente.',
  'customers.view.table': 'Tabela',
  'customers.view.kanban': 'Kanban',
  // Título da própria página de listagem (customers/list/index.tsx) — "Tabela"
  // (customers.view.table) é o rótulo curto da aba do toggle, não serve como
  // título de página/breadcrumb.
  'customers.list.title': 'Listagem',
  // Card index de customers/processes (hub de navegação, mesmo padrão do
  // settings/index.tsx de referência) — indica que não há destino genérico
  // pra Process sem escolher um cliente primeiro.
  'process.index.hint': 'Selecione um cliente para ver ou criar processos.',
  'private.role': 'Papel',
  // Usado por BreadcrumbEllipsis (apps/web/src/components/ui/breadcrumb.tsx,
  // T8) — texto de acessibilidade (sr-only) do "..." de breadcrumbs longos.
  more: 'Mais',
  home: 'Início',
  // aria-label do <nav> da dock de navegação mobile (mobile-dock.tsx) — não
  // pode ficar sem rótulo já que coexiste na tela com o <nav
  // aria-label="breadcrumb"> do Card.
  'nav.primary': 'Navegação principal',
  // Inbox (feature inbox-realtime, Fase 11) — chaves novas usadas por
  // routes/_private/inbox/** (index.tsx + @components/*).
  'inbox.title': 'Caixa de entrada',
  'inbox.queue.title': 'Fila de conversas',
  'inbox.thread.select_hint': 'Selecione uma conversa na fila para ver o histórico.',
  'inbox.thread.not_found': 'Conversa não encontrada nesta página da fila. Ajuste os filtros ou a paginação.',
  'inbox.column.customer': 'Cliente',
  'inbox.column.mode': 'Modo',
  'inbox.column.assignee': 'Responsável',
  'inbox.column.last_activity': 'Última atividade',
  'inbox.column.unread': 'Não lida',
  'inbox.column.window': 'Janela 24h',
  'inbox.mode.bot': 'Bot',
  'inbox.mode.human': 'Humano',
  'inbox.assignee.you': 'Você',
  'inbox.assignee.other': 'Outro operador',
  'inbox.unread.yes': 'Nova',
  'inbox.window.open': 'Aberta',
  'inbox.window.closed': 'Fechada',
  'inbox.filter.mode.all': 'Todas',
  'inbox.thread.empty': 'Nenhuma mensagem ainda.',
  'inbox.message.unsupported': 'Tipo de mensagem não suportado nesta tela.',
  'inbox.message.failed': 'Falhou',
  'inbox.media.view': 'Ver',
  'inbox.media.download': 'Baixar',
  'inbox.media.loading': 'Carregando mídia…',
  'inbox.media.error': 'Não foi possível carregar essa mídia agora.',
  'inbox.composer.window_closed': 'A janela de 24h está fechada. Continue a conversa pelo seu WhatsApp.',
  'inbox.composer.open_whatsapp': 'Abrir no WhatsApp',
  'inbox.composer.placeholder': 'Escreva uma mensagem…',
  'inbox.composer.send': 'Enviar',
  'inbox.composer.error': 'Não foi possível enviar a mensagem.',
  'inbox.resend.action': 'Reenviar',
  'inbox.takeover.action': 'Assumir',
  'inbox.takeover.error': 'Não foi possível assumir esta conversa.',
  'inbox.release.action': 'Liberar',
  'inbox.release.error': 'Não foi possível liberar esta conversa.',
  // Catálogo de produtos (feature catalog-orders, Fase 9) — chaves novas
  // usadas por routes/_private/products/** (T19).
  'product.list.title': 'Catálogo',
  'product.price': 'Preço',
  'product.stock': 'Estoque',
  'product.status.active': 'Ativo',
  'product.status.inactive': 'Inativo',
  // T20 — products/add/index.tsx.
  'product.create.title': 'Novo produto',
  'product.create.error': 'Não foi possível criar o produto.',
  'product.sku': 'SKU',
  'product.description': 'Descrição',
  // T21 — products/details.tsx.
  'product.details.title': 'Detalhe do produto',
  // Fila/histórico de Pedidos (feature catalog-orders, Fase 10) — chaves
  // novas usadas por routes/_private/orders/index.tsx (T23) e pelo card
  // inline do Inbox (order-card.tsx, T24).
  'order.list.title': 'Pedidos',
  'order.column.customer': 'Cliente',
  'order.column.items': 'Itens',
  'order.column.total': 'Total',
  'order.status.pending_approval': 'Pendente',
  'order.status.confirmed': 'Confirmado',
  'order.status.rejected': 'Rejeitado',
  'order.approve.action': 'Aprovar',
  'order.approve.error': 'Não foi possível aprovar o pedido.',
  'order.reject.action': 'Rejeitar',
  'order.reject.error': 'Não foi possível rejeitar o pedido.',
  // Status de pagamento (feature payments-asaas, P2/T31) — read-only,
  // ao lado do status do Order na tela de Pedidos (spec.md P2 AC1).
  'order.status.payment_expired': 'Pagamento expirado',
  'order.column.payment': 'Pagamento',
  'order.payment.pending': 'Pagamento pendente',
  'order.payment.paid': 'Pago',
  'order.payment.expired': 'Cobrança expirada',
  'order.payment.refunded': 'Reembolsado',
  'order.payment.canceled': 'Cancelado',
  // Grade semanal de Professional (feature scheduling, Fase 7/T33) —
  // weekday-editor.tsx agrupa `weeklySchedule` por dia da semana.
  'weekday.0': 'Domingo',
  'weekday.1': 'Segunda-feira',
  'weekday.2': 'Terça-feira',
  'weekday.3': 'Quarta-feira',
  'weekday.4': 'Quinta-feira',
  'weekday.5': 'Sexta-feira',
  'weekday.6': 'Sábado',
  'schedule.window.start': 'Início',
  'schedule.window.end': 'Fim',
  // Telas de Profissional (feature scheduling, Fase 7/T34) — routes/_private/
  // schedule/professionals/**.
  'professional.list.title': 'Profissionais',
  'professional.create.title': 'Novo profissional',
  'professional.details.title': 'Detalhe do profissional',
  'professional.slot_duration': 'Duração do horário (min)',
  'professional.weekly_schedule': 'Grade semanal',
  'professional.status.active': 'Ativo',
  'professional.status.inactive': 'Inativo',
  'professional.filter.show_inactive': 'Mostrar inativos',
  // Telas de Ambiente (feature scheduling, Fase 7/T35) — routes/_private/
  // schedule/spaces/**.
  'space.list.title': 'Ambientes',
  'space.create.title': 'Novo ambiente',
  'space.details.title': 'Detalhe do ambiente',
  'space.status.active': 'Ativo',
  'space.status.inactive': 'Inativo',
  'space.filter.show_inactive': 'Mostrar inativos',
  // Configuração da agenda (feature scheduling, Fase 7/T36) — routes/
  // _private/schedule/settings/index.tsx.
  'scheduling_settings.title': 'Configuração da agenda',
  'scheduling_settings.max_slots': 'Máximo de horários por resposta',
  // Calendário da agenda (feature scheduling, Fase 8/T39) — routes/_private/
  // schedule/calendar/index.tsx.
  'calendar.title': 'Calendário',
  'calendar.previous_week': 'Semana anterior',
  'calendar.next_week': 'Próxima semana',
  'calendar.filter.professional': 'Profissional',
  'calendar.filter.all_professionals': 'Todos os profissionais',
  'calendar.filter.space': 'Ambiente',
  'calendar.filter.all_spaces': 'Todos os ambientes',
  // Diálogo de agendamento (feature scheduling, Fase 8/T40) — routes/_private/
  // schedule/calendar/@components/appointment-dialog.tsx.
  'appointment.create.title': 'Novo agendamento',
  'appointment.detail.title': 'Agendamento',
  'appointment.field.customer': 'Cliente',
  'appointment.field.professional': 'Profissional',
  'appointment.field.date': 'Data',
  'appointment.field.time': 'Hora',
  'appointment.field.space': 'Ambiente',
  'appointment.field.space_none': 'Sem ambiente',
  'appointment.field.notes': 'Observações',
  'appointment.status.pending': 'Pendente',
  'appointment.status.confirmed': 'Confirmado',
  'appointment.status.completed': 'Concluído',
  'appointment.status.no_show': 'Não compareceu',
  'appointment.status.canceled_by_customer': 'Cancelado pelo cliente',
  'appointment.status.canceled_by_operator': 'Cancelado pelo operador',
  'appointment.action.cancel': 'Cancelar agendamento',
  'appointment.cancel.reason_placeholder': 'Motivo (opcional)',
  'appointment.action.reschedule': 'Remarcar',
  'appointment.attendance.completed': 'Compareceu',
  'appointment.attendance.no_show': 'Não compareceu',
  'appointment.action.request_confirmation': 'Pedir confirmação',
};

export const t = (key: string): string => translations[key] ?? key;
